maze:
  world: Survival
  hardcore-switch:
    x: 0
    y: 0
    z: 0
  upper-limit:
    x: 10
    y: 100
    z: 10
  lower-limit:
    x: 20
    y: 90
    z: 20

treasure:
  total:
  common:
    1:
      x: 0.0
      y: 0.0
      z: 0.0
    2:
      x: 0.0
      y: 0.0
      z: 0.0
    3:
      x: 0.0
      y: 0.0
      z: 0.0
    4:
      x: 0.0
      y: 0.0
      z: 0.0
  uncommon:
    1:
      x: 0.0
      y: 0.0
      z: 0.0
    2:
      x: 0.0
      y: 0.0
      z: 0.0
    3:
      x: 0.0
      y: 0.0
      z: 0.0
    4:
      x: 0.0
      y: 0.0
      z: 0.0
  rare:
    1:
      x: 0.0
      y: 0.0
      z: 0.0